from gaia_get_star_info import fetch_and_print_star_data


# 1. Resolve Sagittarius (Sag) star names to precise ICRS positions via SIMBAD
names = [
    "Alpha Sgr",
    "Beta1 Sgr",
    "Beta2 Sgr",
    "Gamma1 Sgr",
    "Gamma2 Sgr",
    "Delta Sgr",
    "Epsilon Sgr",
    "Zeta Sgr",
    "Eta Sgr",
    "Theta1 Sgr",
    "Theta2 Sgr",
    "Iota Sgr",
    "Kappa1 Sgr",
    "Kappa2 Sgr",
    "Lambda Sgr",
    "Mu Sgr",
    "Nu1 Sgr",
    "Nu2 Sgr",
    "Xi1 Sgr",
    "Xi2 Sgr",
    "Omicron Sgr",
    "Pi Sgr",
    "Rho1 Sgr",
    "Rho2 Sgr",
    "Sigma Sgr",
    "Tau Sgr",
    "Upsilon Sgr",
    "Phi Sgr",
    "Chi1 Sgr",
    "Chi3 Sgr",
    "Psi Sgr",
    "Omega Sgr",
    "52 Sgr",
    "59 Sgr",
    "60 Sgr",
    "62 Sgr",
    "11 Sgr",
    "14 Sgr",
    "15 Sgr",
    "16 Sgr",
    "21 Sgr",
    "29 Sgr",
    "30 Sgr",
    "33 Sgr",
    "37 Sgr",
    "43 Sgr",
    "50 Sgr",
    "51 Sgr",
    "61 Sgr",
    "63 Sgr",
    "W Sgr",
    "X Sgr",
    "Y Sgr"
]

fetch_and_print_star_data(names)
